// badword.js — Foolproof Tamper-Proof Profanity Filter
// Version: 4.0.0 (Forge Edition)
//
// A self-contained, drop-in profanity filter that normalizes away
// text tricks before matching: leetspeak, inserted spaces/punctuation,
// repeated characters, unicode lookalikes, mixed case, zero-width
// characters, diacritics, and homoglyphs.
//
// =============================================================================
// FEATURES
// =============================================================================
// - 2000+ bad words across multiple categories
// - Multi-pass normalization (NFKD, diacritics, zero-width, leet, separators,
//   short-token merging, repeated-character collapsing)
// - Boundary-anchored regex matching (no false positives on "class", "grass")
// - Tamper-proof: closure isolation, integrity check, frozen API
// - Self-healing: MutationObserver re-attaches filter if removed
// - Anti-debug: timing detection
// - Secret override: single hidden command to disable
//
// =============================================================================
// TAMPER-PROOF ARCHITECTURE
// =============================================================================
// The filter runs inside an IIFE closure. All internal functions, regex
// objects, and the word list are private — they cannot be accessed or
// modified from the browser console (dev tools).
//
// The public API (window.containsBadWords, etc.) is frozen with
// Object.freeze, so it cannot be reassigned. Even if someone overwrites
// window.containsBadWords, the auto-attach handlers use the PRIVATE
// closure reference, not the global one — so the filter keeps working.
//
// An integrity check verifies the word list at runtime. If someone
// modifies the array (e.g., emptying it via dev tools), the filter
// detects the tampering and rebuilds from an internal backup.
//
// A MutationObserver watches the DOM for new inputs and re-attaches
// the filter. If someone removes an event listener, the observer
// re-adds it on the next mutation cycle.
//
// =============================================================================
// SECRET OVERRIDE
// =============================================================================
// The ONLY way to disable the filter from dev tools is:
// Any other key string is rejected. Overwriting the function itself
// does not disable the filter — the internal _disabled flag lives
// in the closure and is only set by the original function.
//
// =============================================================================
// USAGE
// =============================================================================
// 1. Include this script on your page:  <script src="badword.js"></script>
// 2. All text inputs, textareas, and contenteditable elements are
//    automatically filtered. Typing a bad word shows a warning modal
//    and clears the field.
// 3. To manually check text:
//      window.containsBadWords("some text")  ->  true / false
// 4. To attach to a specific input:
//      window.attachFilterToInput(element)
// 5. To attach to all inputs on a page:
//      window.attachFilterToAllInputs()
// 6. Secret override (dev tools only):
//
// =============================================================================
// NORMALIZATION PIPELINE
// =============================================================================
// Input text goes through these steps before matching:
//   1. Lowercase
//   2. NFKD Unicode normalization (separates base chars from diacritics)
//   3. Strip diacritics + non-ASCII (removes accents, foreign scripts)
//   4. Remove zero-width characters (U+200B, U+200C, U+200D, U+FEFF, U+00AD)
//   5. Leet/homoglyph mapping (optional — @ -> a, 3 -> e, 1 -> i, etc.)
//   6. Strip non-alpha separators (keeps only a-z, 0-9, space)
//   7. Collapse spaces + trim
//   8. Merge short-token runs (f u c k -> fuck)
//   9. Collapse repeated characters (fuuuck -> fuck)
// The resulting space-delimited token stream is matched against a
// word-boundary-anchored regex.
// Two regexes are built: one with leet mapping, one without (to catch
// numeric patterns like "420" that leet mapping would destroy).
//
// =============================================================================

(function () {
  'use strict';

  // ===========================================================================
  // BAD WORDS LIST
  // ===========================================================================
  // Organized by category. Duplicates and leetspeak variants are auto-merged
  // at runtime by the regex builder (normalized forms are deduplicated).
  // One word per line for maintainability. Add words freely — the builder
  // handles normalization and deduplication automatically.
  // ===========================================================================

  var badWords = [

    // =========================================================================
    // CORE PROFANITY — swear words and their morphological variants
    // =========================================================================
    "fuck",
    "fucking",
    "fucked",
    "fucker",
    "fuckers",
    "fuckoff",
    "fuckyou",
    "fuckhead",
    "fuckface",
    "fuckass",
    "fucknut",
    "fuckstick",
    "fuckwad",
    "fucknugget",
    "fuckbrain",
    "fuckwit",
    "fucktard",
    "fucka",
    "fuckin",
    "fuckedup",
    "fuckbucket",
    "fuckass",
    "fucknut",
    "fuk",
    "fck",
    "fukin",
    "fcking",
    "fking",
    "fux",
    "fuxk",
    "fuking",
    "fuked",
    "fukker",
    "fuk3d",
    "fcuk",
    "fcku",
    "phuck",
    "phuk",
    "ph4ck",
    "f0ck",
    "f0k",
    "f4ck",
    "motherfucker",
    "mothafucker",
    "motherfuck",
    "motherfukin",
    "motherfuckin",
    "motherfucking",
    "muthafucka",
    "muthafucker",
    "mothafucka",
    "motherless",
    "mf",
    "mofos",
    "mofo",
    "mfer",
    "m0fo",
    "shit",
    "shitty",
    "shitface",
    "shithead",
    "bullshit",
    "shits",
    "shitshow",
    "shitstorm",
    "shitstain",
    "shitheel",
    "shitbird",
    "shitlord",
    "shitbrain",
    "shithole",
    "shitting",
    "shitass",
    "shitbag",
    "shitkicker",
    "dipshit",
    "horseshit",
    "dogshit",
    "eatshit",
    "pieceofshit",
    "shitforbrains",
    "shit-for-brains",
    "sh1t",
    "sh!t",
    "5hit",
    "5h1t",
    "$hit",
    "ass",
    "asshole",
    "assholes",
    "asshat",
    "asswipe",
    "dumbass",
    "smartass",
    "jackass",
    "badass",
    "fatass",
    "lazyass",
    "kissass",
    "assclown",
    "asskisser",
    "assmonger",
    "assface",
    "assgoblin",
    "assmonkey",
    "asspirate",
    "asswad",
    "assbanger",
    "assbite",
    "assjacker",
    "asshopper",
    "painintheass",
    "kissmyass",
    "eatmyass",
    "bitch",
    "bitches",
    "bitchy",
    "sonofabitch",
    "sonsabitch",
    "biatch",
    "b1tch",
    "b!tch",
    "8itch",
    "b1tchy",
    "shutupbitch",
    "cunt",
    "cunts",
    "twat",
    "cuntface",
    "cuntbag",
    "cuntish",
    "cunting",
    "thundercunt",
    "twatwaffle",
    "twathead",
    "twunt",
    "tw4t",
    "dick",
    "dickhead",
    "dickwad",
    "dickbag",
    "dickface",
    "dickhole",
    "dickjuice",
    "dickmilk",
    "dickslap",
    "dickweed",
    "dickless",
    "prick",
    "pricks",
    "d1ck",
    "d!ck",
    "d!ckhead",
    "pussy",
    "pussies",
    "pusy",
    "puss",
    "pussie",
    "cock",
    "cocksucker",
    "cockhead",
    "cockbite",
    "cockface",
    "cockjockey",
    "cockknoker",
    "cockmongler",
    "cockmunch",
    "cocknugget",
    "cocksuck",
    "c0ck",
    "c0ckhead",
    "cockbreath",
    "bastard",
    "bastards",
    "bastardized",
    "bastardly",
    "damn",
    "dammit",
    "damnit",
    "goddamn",
    "goddamnit",
    "hell",
    "whatthehell",
    "gotohell",
    "rotinhell",
    "screw",
    "screwy",
    "screwoff",
    "screwup",
    "screwball",
    "screwyou",
    "kissmyass",
    "eatshit",
    "eatshit",
    "gotohell",
    "getbent",
    "dropdead",
    "biteme",
    "suckit",
    "pieceofcrap",
    "sonofagun",

    // =========================================================================
    // SEXUAL / EXPLICIT TERMS
    // =========================================================================
    "anal",
    "anilingus",
    "anus",
    "arse",
    "arsehole",
    "assfucker",
    "asslick",
    "assmunch",
    "ballbag",
    "ballsack",
    "blowjob",
    "blumpkin",
    "boob",
    "boobs",
    "boobies",
    "bukakke",
    "bukkake",
    "clit",
    "clitoris",
    "cum",
    "cumbubble",
    "cumshot",
    "cumdumpster",
    "cumguzzler",
    "cunnilingus",
    "deepthroat",
    "dildo",
    "ejaculate",
    "ejakulate",
    "erection",
    "erect",
    "faggot",
    "fag",
    "faggit",
    "fanny",
    "fannyflaps",
    "fannyfucker",
    "fistfuck",
    "gangbang",
    "gangbanged",
    "handjob",
    "horny",
    "jizz",
    "jiz",
    "jism",
    "labia",
    "masturbate",
    "masterbate",
    "milf",
    "orgasm",
    "orgy",
    "penis",
    "porn",
    "porno",
    "pornos",
    "prostitute",
    "rimjob",
    "rimming",
    "scat",
    "semen",
    "sex",
    "slut",
    "slutty",
    "slutbag",
    "slutface",
    "skank",
    "skanky",
    "snatch",
    "tit",
    "tits",
    "titties",
    "titty",
    "titfuck",
    "vagina",
    "vulva",
    "whore",
    "whorish",
    "whores",
    "boner",
    "boners",
    "shaft",
    "rod",
    "junk",
    "nutting",
    "nutsack",
    "balls",
    "ballsy",
    "creampie",
    "fellatio",
    "footjob",
    "frotting",
    "grope",
    "hardcore",
    "hentai",
    "ecchi",
    "jackoff",
    "jerkoff",
    "knob",
    "knobhead",
    "muff",
    "muffdiver",
    "pecker",
    "pegging",
    "schlong",
    "scissoring",
    "skeet",
    "spunk",
    "strapon",
    "wank",
    "wanker",
    "wang",
    "willy",
    "yaoi",
    "chode",
    "choad",
    "cawk",
    "kawk",
    "gooch",
    "ho",
    "hoe",
    "hoebag",
    "hoeass",
    "thot",
    "thots",
    "thottie",
    "hooker",
    "hookers",
    "sluts",
    "dyke",
    "dike",
    "lesbo",
    "queer",
    "queerbait",
    "fag",
    "faggot",
    "faggit",
    "fannyfucker",
    "fudgepacker",
    "flamer",
    "felch",
    "fellatio",
    "fingerbang",
    "fingerfuck",
    "footjob",
    "frotting",
    "gangbanged",
    "gaysex",
    "goddamn",
    "grope",
    "handjob",
    "hardcore",
    "hentai",
    "heshe",
    "hoe",
    "hooker",
    "horny",
    "incest",
    "jackoff",
    "jailbait",
    "jerkoff",
    "jism",
    "jiz",
    "jizz",
    "kinky",
    "lust",
    "nympho",
    "orgasm",
    "orgy",
    "pedophile",
    "paedophile",
    "pegging",
    "phuck",
    "phuk",
    "pieceofshit",
    "pigfucker",
    "piss",
    "poon",
    "poonani",
    "poontang",
    "poop",
    "pornos",
    "prick",
    "pthc",
    "pube",
    "punanny",
    "punta",
    "pusy",
    "queef",
    "queer",
    "quim",
    "rape",
    "rapist",
    "rimming",
    "sadism",
    "santorum",
    "schlong",
    "scissoring",
    "shag",
    "shagger",
    "shemale",
    "shibari",
    "snatch",
    "snowballing",
    "sodomize",
    "spunk",
    "strapon",
    "sucker",
    "titty",
    "tosser",
    "tranny",
    "turd",
    "twink",
    "upskirt",
    "v14gra",
    "va-j-j",
    "viagra",
    "voyeur",
    "vulva",
    "wank",
    "wanker",
    "yaoi",
    "zoophilia",
    "beastiality",
    "bestiality",
    "childporn",
    "cp",
    "molester",
    "m0lester",
    "didler",
    "bondage",
    "bdsm",
    "domination",
    "submissive",
    "fisting",
    "fingering",
    "moaning",
    "moan",
    "groan",
    "aroused",
    "fetish",

    // =========================================================================
    // RACIAL / ETHNIC SLURS & DEROGATORY TERMS
    // =========================================================================
    "nigger",
    "nigga",
    "nigg",
    "niggas",
    "niggaz",
    "n1gga",
    "n1gger",
    "niglet",
    "nignog",
    "negr",
    "nigguh",
    "niggur",
    "nig",
    "kneegrow",
    "africoon",
    "niggah",
    "nigg3r",
    "nigg4",
    "n1g",
    "n1gg3r",
    "nigg",
    "chink",
    "chinky",
    "chinkster",
    "ch1nk",
    "gook",
    "gookeye",
    "gookster",
    "g00k",
    "zipperhead",
    "slant",
    "slanteye",
    "slope",
    "dink",
    "nip",
    "kike",
    "kyke",
    "kikester",
    "k1ke",
    "hymie",
    "sheeny",
    "yid",
    "heeb",
    "hebe",
    "hooknose",
    "spic",
    "spick",
    "sp1c",
    "greaser",
    "wetback",
    "wetbackster",
    "w3tback",
    "beaner",
    "beaners",
    "b3aner",
    "tacobender",
    "borderbunny",
    "mexcrement",
    "porchmonkey",
    "jigaboo",
    "junglebunny",
    "junglebunny",
    "spearchucker",
    "spook",
    "darkie",
    "tarbaby",
    "coon",
    "c00n",
    "j1gaboo",
    "sandnigger",
    "cameljockey",
    "hajji",
    "haji",
    "hadji",
    "dunecoon",
    "bombmaker",
    "diaperhead",
    "raghead",
    "raghead",
    "r4ghead",
    "towelhead",
    "t0welhead",
    "currymuncher",
    "dothead",
    "streetshitter",
    "streetshitter",
    "pajeet",
    "currynigger",
    "honky",
    "honkey",
    "whitey",
    "redneck",
    "trailertrash",
    "hillbilly",
    "whitetrash",
    "peckerwood",
    "ofay",
    "gringo",
    "haole",
    "paleface",
    "roundeye",
    "whitedevil",
    "kraut",
    "hun",
    "fritz",
    "jerry",
    "frog",
    "froggy",
    "limey",
    "pom",
    "pommy",
    "wog",
    "wop",
    "dago",
    "guido",
    "guinea",
    "greaseball",
    "eyetie",
    "pikey",
    "gypsy",
    "chav",
    "abbo",
    "boong",
    "ruski",
    "commie",
    "chingchong",
    "chingchong",
    "oriental",
    "squint",
    "yellowperil",
    "gong",
    "jook",
    "buckwheat",
    "charcoal",
    "coalburner",
    "ebony",
    "mooncricket",
    "pickaninny",
    "sambo",
    "shine",
    "smokedirish",
    "snowflake",
    "spick",
    "spickster",
    "mojado",
    "tacohead",
    "kebab",
    "muzzie",
    "sandmonkey",
    "turbanator",
    "bimbo",
    "cholo",
    "eskimo",
    "injun",
    "redskin",
    "squaw",
    "timbernigger",
    "wagonburner",
    "ricenigger",
    "ricepicker",
    "yellow",
    "monkey",
    "gorilla",
    "ape",
    "savage",
    "nazi",
    "negro",
    "neonazi",
    "swastika",

    // -- merged from forge word data + compound/suffix/leet expansions --
    "fuck",
    "fucking",
    "fucked",
    "fucker",
    "fuckers",
    "fuckoff",
    "fuckyou",
    "fuk",
    "fck",
    "fuckin",
    "fukin",
    "fcking",
    "fking",
    "fuckwit",
    "fuckface",
    "fuckass",
    "fucknut",
    "fuckstick",
    "fuckwad",
    "fucknugget",
    "fuckbrain",
    "fuckhead",
    "fucktard",
    "fucka",
    "fuckedup",
    "motherfucker",
    "mothafucker",
    "motherfuck",
    "motherfukin",
    "motherfuckin",
    "muthafucka",
    "muthafucker",
    "mothafucka",
    "mf",
    "mofos",
    "mofo",
    "mfer",
    "m0fo",
    "shit",
    "shitty",
    "shitface",
    "shithead",
    "bullshit",
    "shits",
    "shitshow",
    "shitstorm",
    "shitstain",
    "shitheel",
    "shitbird",
    "shitlord",
    "shitbrain",
    "shithole",
    "shitting",
    "dipshit",
    "horseshit",
    "dogshit",
    "eatshit",
    "eat shit",
    "shitass",
    "shitbag",
    "shitkicker",
    "piece of shit",
    "pieceofshit",
    "s_h_i_t",
    "s hit",
    "sh1t",
    "sh!t",
    "5hit",
    "5h1t",
    "ass",
    "asshole",
    "assholes",
    "asshat",
    "asswipe",
    "dumbass",
    "smartass",
    "jackass",
    "badass",
    "fatass",
    "lazyass",
    "kissass",
    "assclown",
    "asskisser",
    "assmonger",
    "assface",
    "assgoblin",
    "assmonkey",
    "asspirate",
    "asswad",
    "assbanger",
    "assbite",
    "assjacker",
    "asshopper",
    "painintheass",
    "kiss my ass",
    "bitch",
    "bitches",
    "bitchy",
    "sonofabitch",
    "biatch",
    "b1tch",
    "b!tch",
    "sonsabitch",
    "bitchy",
    "shut up bitch",
    "cunt",
    "cunts",
    "twat",
    "cuntface",
    "cuntbag",
    "cuntish",
    "cunting",
    "thundercunt",
    "twatwaffle",
    "twathead",
    "twunt",
    "tw4t",
    "dick",
    "dickhead",
    "dickwad",
    "dickbag",
    "dickface",
    "dickhole",
    "dickjuice",
    "dickmilk",
    "dickslap",
    "dickweed",
    "dickless",
    "dickwad",
    "prick",
    "pricks",
    "pussy",
    "pussies",
    "pusy",
    "puss",
    "pussie",
    "cock",
    "cocksucker",
    "cockhead",
    "cockbite",
    "cockface",
    "cockjockey",
    "cockknoker",
    "cockmongler",
    "cockmunch",
    "cocknugget",
    "cocksuck",
    "c0ck",
    "c0ckhead",
    "cockbreath",
    "bastard",
    "bastards",
    "bastardized",
    "bastardly",
    "motherless",
    "damn",
    "dammit",
    "goddamn",
    "goddamnit",
    "hell",
    "what the hell",
    "go to hell",
    "rot in hell",
    "screw",
    "screw you",
    "screw off",
    "screwup",
    "screwball",
    "anal",
    "anilingus",
    "anus",
    "arse",
    "arsehole",
    "assfucker",
    "asslick",
    "assmunch",
    "ballbag",
    "ballsack",
    "blowjob",
    "blumpkin",
    "boob",
    "boobs",
    "boobies",
    "bukakke",
    "bukkake",
    "clit",
    "clitoris",
    "cum",
    "cumbubble",
    "cumshot",
    "cumdumpster",
    "cumguzzler",
    "cunnilingus",
    "deepthroat",
    "dildo",
    "ejaculate",
    "ejakulate",
    "erection",
    "erect",
    "faggot",
    "fag",
    "faggit",
    "fanny",
    "fannyflaps",
    "fannyfucker",
    "fistfuck",
    "gangbang",
    "gangbanged",
    "handjob",
    "horny",
    "jizz",
    "jiz",
    "jism",
    "labia",
    "masturbate",
    "masterbate",
    "milf",
    "orgasm",
    "orgy",
    "penis",
    "porn",
    "porno",
    "pornos",
    "prostitute",
    "rimjob",
    "rimming",
    "scat",
    "semen",
    "sex",
    "sex",
    "slut",
    "slutty",
    "slutbag",
    "slutface",
    "skank",
    "skanky",
    "snatch",
    "tit",
    "tits",
    "titties",
    "titty",
    "titfuck",
    "vagina",
    "vulva",
    "whore",
    "whorish",
    "boner",
    "boners",
    "shaft",
    "rod",
    "junk",
    "nutting",
    "nutsack",
    "balls",
    "ballsy",
    "creampie",
    "fellatio",
    "footjob",
    "frotting",
    "grope",
    "handjob",
    "hardcore",
    "hentai",
    "ecchi",
    "jackoff",
    "jerkoff",
    "knob",
    "knobhead",
    "muff",
    "muffdiver",
    "pecker",
    "pegging",
    "schlong",
    "scissoring",
    "skeet",
    "spunk",
    "strapon",
    "wank",
    "wanker",
    "wang",
    "willy",
    "yaoi",
    "boner",
    "chode",
    "choad",
    "cawk",
    "kawk",
    "gooch",
    "skank",
    "ho",
    "hoe",
    "hoebag",
    "thot",
    "thots",
    "thottie",
    "hooker",
    "hookers",
    "sluts",
    "whores",
    "dyke",
    "dike",
    "lesbo",
    "queer",
    "queerbait",
    "fag",
    "faggot",
    "faggit",
    "fanny",
    "fart",
    "felch",
    "flamer",
    "fook",
    "nigger",
    "nigga",
    "nigg",
    "niggas",
    "niggaz",
    "n1gga",
    "n1gger",
    "niglet",
    "nignog",
    "negr",
    "nigguh",
    "niggur",
    "nig",
    "kneegrow",
    "africoon",
    "niggah",
    "nigg3r",
    "nigg4",
    "n1g",
    "n1gg3r",
    "chink",
    "chinky",
    "chinkster",
    "ch1nk",
    "gook",
    "gookeye",
    "gookster",
    "g00k",
    "zipperhead",
    "slant",
    "slanteye",
    "slope",
    "dink",
    "nip",
    "gook",
    "kike",
    "kyke",
    "kikester",
    "k1ke",
    "hymie",
    "sheeny",
    "yid",
    "heeb",
    "hebe",
    "hooknose",
    "spic",
    "spick",
    "sp1c",
    "greaser",
    "wetback",
    "wetbackster",
    "w3tback",
    "beaner",
    "beaners",
    "b3aner",
    "taco bender",
    "border bunny",
    "mexcrement",
    "porchmonkey",
    "jigaboo",
    "junglebunny",
    "jungle bunny",
    "spear chucker",
    "spook",
    "darkie",
    "tar baby",
    "coon",
    "c00n",
    "j1gaboo",
    "sand nigger",
    "sandnigger",
    "camel jockey",
    "hajji",
    "haji",
    "hadji",
    "dune coon",
    "bomb maker",
    "diaper head",
    "raghead",
    "rag head",
    "r4ghead",
    "towelhead",
    "t0welhead",
    "curry muncher",
    "dot head",
    "dothead",
    "street shitter",
    "streetshitter",
    "pajeet",
    "curry nigger",
    "honky",
    "honkey",
    "honky",
    "whitey",
    "redneck",
    "trailer trash",
    "hillbilly",
    "white trash",
    "peckerwood",
    "ofay",
    "gringo",
    "haole",
    "paleface",
    "roundeye",
    "white devil",
    "kraut",
    "hun",
    "fritz",
    "jerry",
    "frog",
    "froggy",
    "limey",
    "pom",
    "pommy",
    "wog",
    "wop",
    "dago",
    "guido",
    "guinea",
    "greaseball",
    "eyetie",
    "pikey",
    "gypsy",
    "chav",
    "abbo",
    "boong",
    "wog",
    "ruski",
    "commie",
    "ching chong",
    "chingchong",
    "oriental",
    "squint",
    "yellow peril",
    "gong",
    "jook",
    "buckwheat",
    "charcoal",
    "coalburner",
    "ebony",
    "moon cricket",
    "pickaninny",
    "sambo",
    "shine",
    "smoked irish",
    "snowflake",
    "spook",
    "spic",
    "spick",
    "sp1c",
    "spickster",
    "mojado",
    "tacohead",
    "kebab",
    "muzzie",
    "sand monkey",
    "turbanator",
    "bimbo",
    "cholo",
    "eskimo",
    "injun",
    "redskin",
    "squaw",
    "timber nigger",
    "wagon burner",
    "rice nigger",
    "rice picker",
    "yellow",
    "monkey",
    "gorilla",
    "ape",
    "savage",
    "nazi",
    "negro",
    "neonazi",
    "swastika",
    "weed",
    "pot",
    "marijuana",
    "cannabis",
    "ganja",
    "kush",
    "maryjane",
    "blunt",
    "joint",
    "doobie",
    "heroin",
    "cocaine",
    "coke",
    "crack",
    "meth",
    "methamphetamine",
    "speed",
    "ice",
    "crystal",
    "mdma",
    "ecstasy",
    "ecstacy",
    "molly",
    "mollys",
    "molley",
    "lsd",
    "acid",
    "shrooms",
    "mushrooms",
    "mushies",
    "ketamine",
    "ket",
    "specialk",
    "special k",
    "k-hole",
    "oxy",
    "oxycodone",
    "oxycontin",
    "oxys",
    "vicodin",
    "vic",
    "percocet",
    "percs",
    "perc",
    "xanax",
    "xannies",
    "xans",
    "xanax bar",
    "xanny",
    "bars",
    "benzo",
    "benzodiazepine",
    "adderall",
    "addies",
    "adderallxr",
    "ritalin",
    "fentanyl",
    "fent",
    "fentalogues",
    "tramadol",
    "codeine",
    "lean",
    "purple drank",
    "sizzurp",
    "syrup",
    "cough syrup",
    "promethazine",
    "opioid",
    "opiate",
    "suboxone",
    "subutex",
    "subbies",
    "zubsolv",
    "buprenorphine",
    "dmt",
    "ayahuasca",
    "huasca",
    "dmt brew",
    "salvia",
    "salvia divinorum",
    "divinorum",
    "ghb",
    "roofies",
    "poppers",
    "nitrous",
    "whippets",
    "amyl nitrite",
    "420",
    "blazed",
    "stoned",
    "baked",
    "tripping",
    "trip",
    "rolling",
    "geeked",
    "zooted",
    "tweaking",
    "fiend",
    "junkie",
    "dope",
    "dopehead",
    "snow",
    "blow",
    "yayo",
    "white",
    "skunk",
    "dabs",
    "wax",
    "shatter",
    "oil",
    "edibles",
    "cart",
    "vape",
    "thc",
    "cbd",
    "thca",
    "thc-a",
    "smack",
    "china white",
    "black tar",
    "boy",
    "horse",
    "speedball",
    "crackhead",
    "methhead",
    "tweeker",
    "pillhead",
    "hydros",
    "norco",
    "roxy",
    "acid tab",
    "blotter",
    "mda",
    "bath salts",
    "bath salt",
    "flakka",
    "research chemicals",
    "synthetic",
    "wock",
    "actavis",
    "dirty sprite",
    "fetty",
    "tranq",
    "xylazine",
    "tranq dope",
    "kratom",
    "mitragyna",
    "tianeptine",
    "gas station heroin",
    "za za red",
    "phenibut",
    "liquid ecstasy",
    "2c-b",
    "2cb",
    "2c-i",
    "2ci",
    "2c-t",
    "nbome",
    "25i",
    "25c",
    "1p-lsd",
    "1cp-lsd",
    "ald-52",
    "dmt cart",
    "dmt vape",
    "changa",
    "mescaline",
    "peyote",
    "san pedro",
    "psilocybin",
    "mushroom chocolate",
    "shroom bar",
    "shroom gummies",
    "dextromethorphan",
    "robotripping",
    "ccc",
    "benadryl",
    "dph",
    "deliriants",
    "delta 8",
    "delta8",
    "delta 9",
    "delta9",
    "live resin",
    "rosin",
    "hash rosin",
    "diamond sauce",
    "terps",
    "dispo",
    "disposable",
    "thc cart",
    "weed pen",
    "gummy",
    "delta gummy",
    "mushroom gummy",
    "alpha pvp",
    "pvp",
    "mdphp",
    "3mmc",
    "3cmc",
    "cathinone",
    "amphetamine",
    "white girl",
    "fent press",
    "fent 30s",
    "blues",
    "m30s",
    "dilaudid",
    "china",
    "subs",
    "bupe",
    "methadone",
    "dolophine",
    "diskettes",
    "klons",
    "kpins",
    "lorazepam",
    "klonopin",
    "ativan",
    "ambien",
    "zombie pill",
    "stilnox",
    "vyanse",
    "vyvanse",
    "concerta",
    "focalin",
    "dexedrine",
    "desoxyn",
    "carfentanil",
    "u47700",
    "etizolam",
    "nitazenes",
    "etonitazene",
    "metonitazene",
    "fentanyl analogues",
    "booze",
    "liquor",
    "drunk",
    "wasted",
    "hammered",
    "rush",
    "jungle juice",
    "nod",
    "nodding",
    "nod out",
    "zombie",
    "perched",
    "roll",
    "molly roll",
    "acid trip",
    "bad trip",
    "hot rail",
    "hotrailing",
    "boof",
    "boofing",
    "plugging",
    "parachute",
    "parachuting",
    "monkey water",
    "fent od",
    "naloxone",
    "gethigh",
    "gettinghigh",
    "snort",
    "snorting",
    "shootup",
    "inject",
    "shooting",
    "popping",
    "smokingweed",
    "poppills",
    "poppingpills",
    "tripballs",
    "rollingface",
    "tweakingout",
    "fiending",
    "jonesing",
    "overdose",
    "overdosing",
    "valium",
    "dopehead",
    "tranny",
    "trannies",
    "trannie",
    "trannys",
    "tr4nny",
    "tr4nnies",
    "tr4nnie",
    "shemale",
    "she-male",
    "shemales",
    "sh3male",
    "sh3males",
    "ladyboys",
    "ladyboy",
    "l4dyboy",
    "l4dyboys",
    "heshe",
    "he-she",
    "he/she",
    "h3-sh3",
    "h3sh3",
    "trap",
    "traps",
    "trapfag",
    "tr@p",
    "tr@ps",
    "shim",
    "chick with a dick",
    "dickgirl",
    "dickgirls",
    "transvestite",
    "transvestites",
    "gender bender",
    "genderbend",
    "troon",
    "troons",
    "troonery",
    "trooncord",
    "troonout",
    "autogynephile",
    "autogynephilia",
    "agp",
    "tims",
    "tifs",
    "transbian",
    "transmaxxing",
    "transmax",
    "hons",
    "clocked",
    "clockable",
    "man in a dress",
    "man in dress",
    "woman in a dress",
    "fake woman",
    "fake man",
    "pretend woman",
    "pretend man",
    "biological male",
    "biological female",
    "chromosomally challenged",
    "delusional",
    "delusional man",
    "delusional woman",
    "xdresser",
    "x-dresser",
    "theyfab",
    "trannyfag",
    "tranniefag",
    "retard",
    "retarded",
    "retards",
    "r tard",
    "rtard",
    "tards",
    "tarded",
    "r3tard",
    "r3t4rd",
    "t4rd",
    "mongoloid",
    "mongol",
    "m0ng",
    "m0ngoloid",
    "spastic",
    "spazzy",
    "spazout",
    "spacker",
    "spack",
    "spacky",
    "sp4z",
    "cripple",
    "crip",
    "crippled",
    "crips",
    "cr1pple",
    "cr1p",
    "gimpy",
    "gimps",
    "g1mp",
    "lamo",
    "lameass",
    "lamebrain",
    "l4me",
    "dumbo",
    "dummies",
    "deaf and dumb",
    "deafmute",
    "idiot",
    "idiots",
    "idiotic",
    "imbecile",
    "imbeciles",
    "1diot",
    "1mbecile",
    "moron",
    "morons",
    "moronic",
    "m0ron",
    "cretin",
    "cretins",
    "feebleminded",
    "feeble minded",
    "simpleton",
    "halfwit",
    "dimwit",
    "nitwit",
    "psychotic",
    "psychopath",
    "psych0",
    "schizophrenic",
    "schiz",
    "sch1zo",
    "crazies",
    "lunatic",
    "loony",
    "loon",
    "nutjob",
    "cr4zy",
    "deranged",
    "d3ranged",
    "mental case",
    "headcase",
    "m3ntal",
    "windowlicker",
    "shortbus",
    "short bus",
    "special ed",
    "sped kid",
    "downie",
    "downy",
    "autist",
    "autismo",
    "aut1st",
    "aut1sm",
    "asperger",
    "aspie",
    "blind as a bat",
    "one eyed",
    "four eyes",
    "bl1nd",
    "midget",
    "dwarf",
    "freakshow",
    "sideshow",
    "handicapped",
    "handicap",
    "wheelchair bound",
    "confined to wheelchair",
    "braindead",
    "brain damaged",
    "vegetative",
    "flid",
    "fliddy",
    "raspberry ripple",
    "harelip",
    "harelipped",
    "clubfoot",
    "hunchback",
    "hunchbacked",
    "baldy",
    "baldie",
    "bucktoothed",
    "slowpoke",
    "slow in the head",
    "slow minded",
    "subnormal",
    "defective",
    "deformed",
    "disfigured",
    "birth defect",
    "epileptic",
    "epileptic fit",
    "seizure boy",
    "leper",
    "leprosy",
    "paralyzed",
    "paralytic",
    "quad",
    "quadriplegic",
    "crippled by",
    "lame excuse",
    "bonkers",
    "batshit",
    "batshit crazy",
    "b4tshit",
    "off your rocker",
    "basket case",
    "fruitcake",
    "nutcase",
    "retard strength",
    "tard wrangler",
    "tard herd",
    "rainman",
    "forrest gump",
    "spec",
    "spec ed",
    "learning disabled",
    "useless eater",
    "d3af",
    "normie",
    "1nsane",
    "gyatt",
    "gyat",
    "gyattt",
    "level10gyatt",
    "level 10 gyatt",
    "huzz",
    "chuzz",
    "chopped huzz",
    "glizzy",
    "304",
    "three oh four",
    "gooner",
    "gooning",
    "goonette",
    "edging",
    "jelq",
    "jelqing",
    "coomer",
    "bomboclat",
    "bombaclat",
    "claat",
    "sybau",
    "syba",
    "fine shyt",
    "big back",
    "zesty",
    "rizzler",
    "skibidi",
    "sigma",
    "mewing",
    "looksmaxxing",
    "looksmax",
    "fanum tax",
    "fanumtax",
    "grimace shake",
    "suika",
    "only in ohio",
    "ohio",
    "mid",
    "npc",
    "based",
    "cope",
    "seethe",
    "skill issue",
    "touch grass",
    "ratio",
    "l bozo",
    "f4ck",
    "f0ck",
    "f0k",
    "fuk3d",
    "ph4ck",
    "phuck",
    "phuk",
    "fcuk",
    "fcku",
    "fux",
    "fuxk",
    "f.u.c.k",
    "f-u-c-k",
    "f_u_c_k",
    "f u c k",
    "f***",
    "f**k",
    "sh1t",
    "sh!t",
    "$hit",
    "5h!t",
    "s.h.i.t",
    "s-h-i-t",
    "s_h_i_t",
    "s h i t",
    "@ss",
    "4ss",
    "4sshole",
    "@sshole",
    "a.s.s",
    "a-s-s",
    "a_s_s",
    "a s s",
    "b1tch",
    "b!tch",
    "8itch",
    "b1tchy",
    "b.i.t.c.h",
    "b-i-t-c-h",
    "b_i_t_c_h",
    "d1ck",
    "d!ck",
    "d!ckhead",
    "d.i.c.k",
    "d-i-c-k",
    "d_i_c_k",
    "c0ck",
    "c0ckhead",
    "cunt3",
    "c.u.n.t",
    "c-u-n-t",
    "c_u_n_t",
    "p1ss",
    "p!ss",
    "tw4t",
    "t\/\/at",
    "a55",
    "5h1t",
    "5hit",
    "go fuck yourself",
    "fuck off",
    "fuck you",
    "what the fuck",
    "for fucks sake",
    "what the hell",
    "shut the hell up",
    "get bent",
    "drop dead",
    "bite me",
    "suck it",
    "piece of crap",
    "son of a gun",
    "screw you",
    "kiss my ass",
    "eat my ass",
    "shut up bitch",
    "piece of shit",
    "son of a bitch",
    "what the fuck",
    "holy shit",
    "holy fuck",
    "no fucking way",
    "abso fucking lutely",
    "un fucking believable",
    "fan fucking tastic",
    "douche",
    "douchebag",
    "douchecanoe",
    "douchelord",
    "scumbag",
    "scumbags",
    "dirtbag",
    "sleazebag",
    "sleazeball",
    "degenerate",
    "pervert",
    "pervy",
    "creep",
    "creeper",
    "weirdo",
    "jackwagon",
    "toolbag",
    "mouthbreather",
    "knucklehead",
    "meathead",
    "blockhead",
    "birdbrain",
    "bozo",
    "trashbag",
    "trashperson",
    "wasteofspace",
    "human garbage",
    "crappy",
    "crud",
    "jerkass",
    "losers",
    "dipfuck",
    "bullshitter",
    "bullshitting",
    "pissing",
    "pisshead",
    "pissface",
    "pissbag",
    "pissweak",
    "piss off",
    "pissedoff",
    "pissed",
    "piss",
    "hoebag",
    "hoeass",
    "bastardized",
    "bastardly",
    "motherless",
    "slutty",
    "skanky",
    "whorish",
    "faggot",
    "fag",
    "faggit",
    "fannyfucker",
    "fudgepacker",
    "flamer",
    "rimming",
    "felch",
    "fellatio",
    "fingerbang",
    "fingerfuck",
    "footjob",
    "frotting",
    "gangbanged",
    "gaysex",
    "goddamn",
    "grope",
    "handjob",
    "hardcore",
    "hentai",
    "heshe",
    "hoe",
    "hooker",
    "horny",
    "incest",
    "jackoff",
    "jailbait",
    "jerkoff",
    "jism",
    "jiz",
    "jizz",
    "kinky",
    "lust",
    "nympho",
    "orgasm",
    "orgy",
    "pedophile",
    "paedophile",
    "pegging",
    "phuck",
    "phuk",
    "piece of shit",
    "pigfucker",
    "piss",
    "poon",
    "poonani",
    "poontang",
    "poop",
    "pornos",
    "prick",
    "pthc",
    "pube",
    "punanny",
    "punta",
    "pusy",
    "queef",
    "queer",
    "quim",
    "rape",
    "rapist",
    "rimming",
    "sadism",
    "santorum",
    "schlong",
    "scissoring",
    "shag",
    "shagger",
    "shemale",
    "shibari",
    "snatch",
    "snowballing",
    "sodomize",
    "spunk",
    "strapon",
    "sucker",
    "titty",
    "tosser",
    "tranny",
    "turd",
    "twink",
    "upskirt",
    "v14gra",
    "va-j-j",
    "viagra",
    "voyeur",
    "vulva",
    "wank",
    "wanker",
    "yaoi",
    "zoophilia",
    "beastiality",
    "bestiality",
    "child porn",
    "cp",
    "kiddo diddler",
    "didler",
    "didler",
    "m0lester",
    "molester",
    "molester",
    "dammit",
    "damn",
    "dam",
    "crap",
    "crappy",
    "crud",
    "fart",
    "farts",
    "farting",
    "barf",
    "barfing",
    "puke",
    "puking",
    "turd",
    "poop",
    "pooping",
    "boob",
    "boobs",
    "boobies",
    "titty",
    "titties",
    "tit",
    "tits",
    "nut",
    "nuts",
    "balls",
    "junk",
    "shaft",
    "rod",
    "boner",
    "boners",
    "erection",
    "erect",
    "horny",
    "lust",
    "kinky",
    "fetish",
    "bondage",
    "bdsm",
    "domination",
    "submissive",
    "fisting",
    "fingering",
    "moaning",
    "moan",
    "groan",
    " aroused",
    "bollocks",
    "shite",
    "bugger",
    "bloody",
    "plonker",
    "slag",
    "slapper",
    "scrubber",
    "minger",
    "mingin",
    "gobshite",
    "bampot",
    "bawbag",
    "numbnuts",
    "dicknose",
    "douchenozzle",
    "douchewaffle",
    "titwank",
    "arsebandit",
    "shitfaced",
    "spunkbucket",
    "jizzbucket",
    "cumbucket",
    "cumslut",
    "circlejerk",
    "jerkcircle",
    "wankstain",
    "wankshaft",
    "wanksock",
    "tosspot",
    "jackshit",
    "apeshit",
    "sidebitch",
    "sidehoe",
    "fuckboy",
    "fuckboi",
    "fuccboi",
    "thotiana",
    "camwhore",
    "cuck",
    "cuckold",
    "cuckservative",
    "jizzler",
    "jizzing",
    "kut",
    "klootzak",
    "tering",
    "tyfus",
    "kanker",
    "kankerlijer",
    "scheisse",
    "fick",
    "arschloch",
    "fotze",
    "hure",
    "schlampe",
    "wichser",
    "schwanz",
    "mistkerl",
    "putain",
    "merde",
    "connard",
    "connasse",
    "salope",
    "niquer",
    "nique",
    "bite",
    "chatte",
    "stronzo",
    "puttana",
    "cazzo",
    "figa",
    "scopare",
    "troia",
    "foder",
    "caralho",
    "bosta",
    "porra",
    "foda",
    "fude",
    "blyat",
    "cyka",
    "suka",
    "pizda",
    "khuy",
    "yebat",
    "malaka",
    "malakas",
    "gago",
    "bobo",
    "tanga",
    "punyeta",
    "ulol",
    "tarantado",
    "tamade",
    "chutiya",
    "bhosdi",
    "bhosdike",
    "gandu",
    "gaand",
    "madarchod",
    "behenchod",
    "randi",
    "kamina",
    "harami",
    "saala",
    "chodu",
    "lund",
    "lauda",
    "kurwa",
    "chuj",
    "skurwysyn",
    "jebac",
    "kurva",
    "orospu",
    "sikerim",
    "fitta",
    "kuk",
    "hora",
    "fitte",
    "dritt",
    "whitepower",
    "heilhitler",
    "siegheil",
    "kkk",
    "1488",
    "shitehawk",
    "fuckwad",
    "fuckwhistle",
    "fucknizzle",
    "dicknoodle",
    "cockwomble",
    "cockbiscuit",
    "twatwaffle",
    "twatburger",
    "cuntbubble",
    "cuntrocket",
    "bitchtits",
    "doucheburger",
    "pissflaps",
    "clitlicker",
    "rimlord",
    "poopchute",
    "spunktrumpet",
    "fucktrumpet",
    "wankpuffin",
    "bollockchops",
    "dickweasel",
    "fuck",
    "fucks",
    "fucky",
    "fucking",
    "fucked",
    "fucker",
    "fuckers",
    "fuckface",
    "fuckhead",
    "fuckbag",
    "fuckwipe",
    "fuckhole",
    "fuckbucket",
    "fucklord",
    "fuks",
    "fuky",
    "fuking",
    "fuked",
    "fuker",
    "fukers",
    "fukface",
    "fukhead",
    "fukbag",
    "fukwipe",
    "fukhole",
    "fukbucket",
    "fuklord",
    "fcks",
    "fcky",
    "fcking",
    "fcked",
    "fcker",
    "fckers",
    "fckface",
    "fckhead",
    "fckbag",
    "fckwipe",
    "fckhole",
    "fckbucket",
    "fcklord",
    "phuk",
    "phuks",
    "phuky",
    "phuking",
    "phuked",
    "phuker",
    "phukers",
    "phukface",
    "phukhead",
    "phukbag",
    "phukwipe",
    "phukhole",
    "phukbucket",
    "phuklord",
    "shit",
    "shits",
    "shity",
    "shiting",
    "shited",
    "shiter",
    "shiters",
    "shitface",
    "shithead",
    "shitbag",
    "shitwipe",
    "shithole",
    "shitbucket",
    "shitlord",
    "shyt",
    "shyts",
    "shyty",
    "shyting",
    "shyted",
    "shyter",
    "shyters",
    "shytface",
    "shythead",
    "shytbag",
    "shytwipe",
    "shythole",
    "shytbucket",
    "shytlord",
    "shite",
    "shites",
    "shitey",
    "shiteing",
    "shiteed",
    "shiteer",
    "shiteers",
    "shiteface",
    "shitehead",
    "shitebag",
    "shitewipe",
    "shitehole",
    "shitebucket",
    "shitelord",
    "piss",
    "pisss",
    "pissy",
    "pissing",
    "pissed",
    "pisser",
    "pissers",
    "pissface",
    "pisshead",
    "pissbag",
    "pisswipe",
    "pisshole",
    "pissbucket",
    "pisslord",
    "arse",
    "arses",
    "arsey",
    "arseing",
    "arseed",
    "arseer",
    "arseers",
    "arseface",
    "arsehead",
    "arsebag",
    "arsewipe",
    "arsehole",
    "arsebucket",
    "arselord",
    "asss",
    "assy",
    "assing",
    "assed",
    "asser",
    "assers",
    "assface",
    "asshead",
    "assbag",
    "asswipe",
    "asshole",
    "assbucket",
    "asslord",
    "bitch",
    "bitchs",
    "bitchy",
    "bitching",
    "bitched",
    "bitcher",
    "bitchers",
    "bitchface",
    "bitchhead",
    "bitchbag",
    "bitchwipe",
    "bitchhole",
    "bitchbucket",
    "bitchlord",
    "twat",
    "twats",
    "twaty",
    "twating",
    "twated",
    "twater",
    "twaters",
    "twatface",
    "twathead",
    "twatbag",
    "twatwipe",
    "twathole",
    "twatbucket",
    "twatlord",
    "cunt",
    "cunts",
    "cunty",
    "cunting",
    "cunted",
    "cunter",
    "cunters",
    "cuntface",
    "cunthead",
    "cuntbag",
    "cuntwipe",
    "cunthole",
    "cuntbucket",
    "cuntlord",
    "dick",
    "dicks",
    "dicky",
    "dicking",
    "dicked",
    "dicker",
    "dickers",
    "dickface",
    "dickhead",
    "dickbag",
    "dickwipe",
    "dickhole",
    "dickbucket",
    "dicklord",
    "prick",
    "pricks",
    "pricky",
    "pricking",
    "pricked",
    "pricker",
    "prickers",
    "prickface",
    "prickhead",
    "prickbag",
    "prickwipe",
    "prickhole",
    "prickbucket",
    "pricklord",
    "cock",
    "cocks",
    "cocky",
    "cocking",
    "cocked",
    "cocker",
    "cockers",
    "cockface",
    "cockhead",
    "cockbag",
    "cockwipe",
    "cockhole",
    "cockbucket",
    "cocklord",
    "pussy",
    "pussys",
    "pussyy",
    "pussying",
    "pussyed",
    "pussyer",
    "pussyers",
    "pussyface",
    "pussyhead",
    "pussybag",
    "pussywipe",
    "pussyhole",
    "pussybucket",
    "pussylord",
    "slut",
    "sluts",
    "sluty",
    "sluting",
    "sluted",
    "sluter",
    "sluters",
    "slutface",
    "sluthead",
    "slutbag",
    "slutwipe",
    "sluthole",
    "slutbucket",
    "slutlord",
    "whore",
    "whores",
    "whorey",
    "whoreing",
    "whoreed",
    "whoreer",
    "whoreers",
    "whoreface",
    "whorehead",
    "whorebag",
    "whorewipe",
    "whorehole",
    "whorebucket",
    "whorelord",
    "skank",
    "skanks",
    "skanky",
    "skanking",
    "skanked",
    "skanker",
    "skankers",
    "skankface",
    "skankhead",
    "skankbag",
    "skankwipe",
    "skankhole",
    "skankbucket",
    "skanklord",
    "slag",
    "slags",
    "slagy",
    "slaging",
    "slaged",
    "slager",
    "slagers",
    "slagface",
    "slaghead",
    "slagbag",
    "slagwipe",
    "slaghole",
    "slagbucket",
    "slaglord",
    "thot",
    "thots",
    "thoty",
    "thoting",
    "thoted",
    "thoter",
    "thoters",
    "thotface",
    "thothead",
    "thotbag",
    "thotwipe",
    "thothole",
    "thotbucket",
    "thotlord",
    "fags",
    "fagy",
    "faging",
    "faged",
    "fager",
    "fagers",
    "fagface",
    "faghead",
    "fagbag",
    "fagwipe",
    "faghole",
    "fagbucket",
    "faglord",
    "faggot",
    "faggots",
    "faggoty",
    "faggoting",
    "faggoted",
    "faggoter",
    "faggoters",
    "faggotface",
    "faggothead",
    "faggotbag",
    "faggotwipe",
    "faggothole",
    "faggotbucket",
    "faggotlord",
    "dyke",
    "dykes",
    "dykey",
    "dykeing",
    "dykeed",
    "dykeer",
    "dykeers",
    "dykeface",
    "dykehead",
    "dykebag",
    "dykewipe",
    "dykehole",
    "dykebucket",
    "dykelord",
    "lesbo",
    "lesbos",
    "lesboy",
    "lesboing",
    "lesboed",
    "lesboer",
    "lesboers",
    "lesboface",
    "lesbohead",
    "lesbobag",
    "lesbowipe",
    "lesbohole",
    "lesbobucket",
    "lesbolord",
    "tranny",
    "trannys",
    "trannyy",
    "trannying",
    "trannyed",
    "trannyer",
    "trannyers",
    "trannyface",
    "trannyhead",
    "trannybag",
    "trannywipe",
    "trannyhole",
    "trannybucket",
    "trannylord",
    "shemale",
    "shemales",
    "shemaley",
    "shemaleing",
    "shemaleed",
    "shemaleer",
    "shemaleers",
    "shemaleface",
    "shemalehead",
    "shemalebag",
    "shemalewipe",
    "shemalehole",
    "shemalebucket",
    "shemalelord",
    "retard",
    "retards",
    "retardy",
    "retarding",
    "retarded",
    "retarder",
    "retarders",
    "retardface",
    "retardhead",
    "retardbag",
    "retardwipe",
    "retardhole",
    "retardbucket",
    "retardlord",
    "spastic",
    "spastics",
    "spasticy",
    "spasticing",
    "spasticed",
    "spasticer",
    "spasticers",
    "spasticface",
    "spastichead",
    "spasticbag",
    "spasticwipe",
    "spastichole",
    "spasticbucket",
    "spasticlord",
    "spaz",
    "spazs",
    "spazy",
    "spazing",
    "spazed",
    "spazer",
    "spazers",
    "spazface",
    "spazhead",
    "spazbag",
    "spazwipe",
    "spazhole",
    "spazbucket",
    "spazlord",
    "cripple",
    "cripples",
    "crippley",
    "crippleing",
    "crippleed",
    "crippleer",
    "crippleers",
    "crippleface",
    "cripplehead",
    "cripplebag",
    "cripplewipe",
    "cripplehole",
    "cripplebucket",
    "cripplelord",
    "moron",
    "morons",
    "morony",
    "moroning",
    "moroned",
    "moroner",
    "moroners",
    "moronface",
    "moronhead",
    "moronbag",
    "moronwipe",
    "moronhole",
    "moronbucket",
    "moronlord",
    "idiot",
    "idiots",
    "idioty",
    "idioting",
    "idioted",
    "idioter",
    "idioters",
    "idiotface",
    "idiothead",
    "idiotbag",
    "idiotwipe",
    "idiothole",
    "idiotbucket",
    "idiotlord",
    "imbecile",
    "imbeciles",
    "imbeciley",
    "imbecileing",
    "imbecileed",
    "imbecileer",
    "imbecileers",
    "imbecileface",
    "imbecilehead",
    "imbecilebag",
    "imbecilewipe",
    "imbecilehole",
    "imbecilebucket",
    "imbecilelord",
    "cretin",
    "cretins",
    "cretiny",
    "cretining",
    "cretined",
    "cretiner",
    "cretiners",
    "cretinface",
    "cretinhead",
    "cretinbag",
    "cretinwipe",
    "cretinhole",
    "cretinbucket",
    "cretinlord",
    "mong",
    "mongs",
    "mongy",
    "monging",
    "monged",
    "monger",
    "mongers",
    "mongface",
    "monghead",
    "mongbag",
    "mongwipe",
    "monghole",
    "mongbucket",
    "monglord",
    "douche",
    "douches",
    "douchey",
    "doucheing",
    "doucheed",
    "doucheer",
    "doucheers",
    "doucheface",
    "douchehead",
    "douchebag",
    "douchewipe",
    "douchehole",
    "douchebucket",
    "douchelord",
    "wank",
    "wanks",
    "wanky",
    "wanking",
    "wanked",
    "wanker",
    "wankers",
    "wankface",
    "wankhead",
    "wankbag",
    "wankwipe",
    "wankhole",
    "wankbucket",
    "wanklord",
    "tosser",
    "tossers",
    "tossery",
    "tossering",
    "tossered",
    "tosserer",
    "tosserers",
    "tosserface",
    "tosserhead",
    "tosserbag",
    "tosserwipe",
    "tosserhole",
    "tosserbucket",
    "tosserlord",
    "schlong",
    "schlongs",
    "schlongy",
    "schlonging",
    "schlonged",
    "schlonger",
    "schlongers",
    "schlongface",
    "schlonghead",
    "schlongbag",
    "schlongwipe",
    "schlonghole",
    "schlongbucket",
    "schlonglord",
    "chode",
    "chodes",
    "chodey",
    "chodeing",
    "chodeed",
    "chodeer",
    "chodeers",
    "chodeface",
    "chodehead",
    "chodebag",
    "chodewipe",
    "chodehole",
    "chodebucket",
    "chodelord",
    "gooch",
    "goochs",
    "goochy",
    "gooching",
    "gooched",
    "goocher",
    "goochers",
    "goochface",
    "goochhead",
    "goochbag",
    "goochwipe",
    "goochhole",
    "goochbucket",
    "goochlord",
    "jizz",
    "jizzs",
    "jizzy",
    "jizzing",
    "jizzed",
    "jizzer",
    "jizzers",
    "jizzface",
    "jizzhead",
    "jizzbag",
    "jizzwipe",
    "jizzhole",
    "jizzbucket",
    "jizzlord",
    "skeet",
    "skeets",
    "skeety",
    "skeeting",
    "skeeted",
    "skeeter",
    "skeeters",
    "skeetface",
    "skeethead",
    "skeetbag",
    "skeetwipe",
    "skeethole",
    "skeetbucket",
    "skeetlord",
    "spunk",
    "spunks",
    "spunky",
    "spunking",
    "spunked",
    "spunker",
    "spunkers",
    "spunkface",
    "spunkhead",
    "spunkbag",
    "spunkwipe",
    "spunkhole",
    "spunkbucket",
    "spunklord",
    "boner",
    "boners",
    "bonery",
    "bonering",
    "bonered",
    "bonerer",
    "bonerers",
    "bonerface",
    "bonerhead",
    "bonerbag",
    "bonerwipe",
    "bonerhole",
    "bonerbucket",
    "bonerlord",
    "nutsack",
    "nutsacks",
    "nutsacky",
    "nutsacking",
    "nutsacked",
    "nutsacker",
    "nutsackers",
    "nutsackface",
    "nutsackhead",
    "nutsackbag",
    "nutsackwipe",
    "nutsackhole",
    "nutsackbucket",
    "nutsacklord",
    "ballbag",
    "ballbags",
    "ballbagy",
    "ballbaging",
    "ballbaged",
    "ballbager",
    "ballbagers",
    "ballbagface",
    "ballbaghead",
    "ballbagbag",
    "ballbagwipe",
    "ballbaghole",
    "ballbagbucket",
    "ballbaglord",
    "poon",
    "poons",
    "poony",
    "pooning",
    "pooned",
    "pooner",
    "pooners",
    "poonface",
    "poonhead",
    "poonbag",
    "poonwipe",
    "poonhole",
    "poonbucket",
    "poonlord",
    "quim",
    "quims",
    "quimy",
    "quiming",
    "quimed",
    "quimer",
    "quimers",
    "quimface",
    "quimhead",
    "quimbag",
    "quimwipe",
    "quimhole",
    "quimbucket",
    "quimlord",
    "turd",
    "turds",
    "turdy",
    "turding",
    "turded",
    "turder",
    "turders",
    "turdface",
    "turdhead",
    "turdbag",
    "turdwipe",
    "turdhole",
    "turdbucket",
    "turdlord",
    "poop",
    "poops",
    "poopy",
    "pooping",
    "pooped",
    "pooper",
    "poopers",
    "poopface",
    "poophead",
    "poopbag",
    "poopwipe",
    "poophole",
    "poopbucket",
    "pooplord",
    "fart",
    "farts",
    "farty",
    "farting",
    "farted",
    "farter",
    "farters",
    "fartface",
    "farthead",
    "fartbag",
    "fartwipe",
    "farthole",
    "fartbucket",
    "fartlord",
    "barf",
    "barfs",
    "barfy",
    "barfing",
    "barfed",
    "barfer",
    "barfers",
    "barfface",
    "barfhead",
    "barfbag",
    "barfwipe",
    "barfhole",
    "barfbucket",
    "barflord",
    "puke",
    "pukes",
    "pukey",
    "pukeing",
    "pukeed",
    "pukeer",
    "pukeers",
    "pukeface",
    "pukehead",
    "pukebag",
    "pukewipe",
    "pukehole",
    "pukebucket",
    "pukelord",
    "nigger",
    "niggers",
    "niggery",
    "niggering",
    "niggered",
    "niggerer",
    "niggerers",
    "niggerface",
    "niggerhead",
    "niggerbag",
    "niggerwipe",
    "niggerhole",
    "niggerbucket",
    "niggerlord",
    "nigga",
    "niggas",
    "niggay",
    "niggaing",
    "niggaed",
    "niggaer",
    "niggaers",
    "niggaface",
    "niggahead",
    "niggabag",
    "niggawipe",
    "niggahole",
    "niggabucket",
    "niggalord",
    "chink",
    "chinks",
    "chinky",
    "chinking",
    "chinked",
    "chinker",
    "chinkers",
    "chinkface",
    "chinkhead",
    "chinkbag",
    "chinkwipe",
    "chinkhole",
    "chinkbucket",
    "chinklord",
    "gook",
    "gooks",
    "gooky",
    "gooking",
    "gooked",
    "gooker",
    "gookers",
    "gookface",
    "gookhead",
    "gookbag",
    "gookwipe",
    "gookhole",
    "gookbucket",
    "gooklord",
    "kike",
    "kikes",
    "kikey",
    "kikeing",
    "kikeed",
    "kikeer",
    "kikeers",
    "kikeface",
    "kikehead",
    "kikebag",
    "kikewipe",
    "kikehole",
    "kikebucket",
    "kikelord",
    "spic",
    "spics",
    "spicy",
    "spicing",
    "spiced",
    "spicer",
    "spicers",
    "spicface",
    "spichead",
    "spicbag",
    "spicwipe",
    "spichole",
    "spicbucket",
    "spiclord",
    "wetback",
    "wetbacks",
    "wetbacky",
    "wetbacking",
    "wetbacked",
    "wetbacker",
    "wetbackers",
    "wetbackface",
    "wetbackhead",
    "wetbackbag",
    "wetbackwipe",
    "wetbackhole",
    "wetbackbucket",
    "wetbacklord",
    "coon",
    "coons",
    "coony",
    "cooning",
    "cooned",
    "cooner",
    "cooners",
    "coonface",
    "coonhead",
    "coonbag",
    "coonwipe",
    "coonhole",
    "coonbucket",
    "coonlord",
    "jigaboo",
    "jigaboos",
    "jigabooy",
    "jigabooing",
    "jigabooed",
    "jigabooer",
    "jigabooers",
    "jigabooface",
    "jigaboohead",
    "jigaboobag",
    "jigaboowipe",
    "jigaboohole",
    "jigaboobucket",
    "jigaboolord",
    "redneck",
    "rednecks",
    "rednecky",
    "rednecking",
    "rednecked",
    "rednecker",
    "redneckers",
    "redneckface",
    "redneckhead",
    "redneckbag",
    "redneckwipe",
    "redneckhole",
    "redneckbucket",
    "rednecklord",
    "honky",
    "honkys",
    "honkyy",
    "honkying",
    "honkyed",
    "honkyer",
    "honkyers",
    "honkyface",
    "honkyhead",
    "honkybag",
    "honkywipe",
    "honkyhole",
    "honkybucket",
    "honkylord",
    "gringo",
    "gringos",
    "gringoy",
    "gringoing",
    "gringoed",
    "gringoer",
    "gringoers",
    "gringoface",
    "gringohead",
    "gringobag",
    "gringowipe",
    "gringohole",
    "gringobucket",
    "gringolord",
    "wops",
    "wopy",
    "woping",
    "woped",
    "woper",
    "wopers",
    "wopface",
    "wophead",
    "wopbag",
    "wopwipe",
    "wophole",
    "wopbucket",
    "woplord",
    "dago",
    "dagos",
    "dagoy",
    "dagoing",
    "dagoed",
    "dagoer",
    "dagoers",
    "dagoface",
    "dagohead",
    "dagobag",
    "dagowipe",
    "dagohole",
    "dagobucket",
    "dagolord",
    "guinea",
    "guineas",
    "guineay",
    "guineaing",
    "guineaed",
    "guineaer",
    "guineaers",
    "guineaface",
    "guineahead",
    "guineabag",
    "guineawipe",
    "guineahole",
    "guineabucket",
    "guinealord",
    "pikey",
    "pikeys",
    "pikeyy",
    "pikeying",
    "pikeyed",
    "pikeyer",
    "pikeyers",
    "pikeyface",
    "pikeyhead",
    "pikeybag",
    "pikeywipe",
    "pikeyhole",
    "pikeybucket",
    "pikeylord",
    "chav",
    "chavs",
    "chavy",
    "chaving",
    "chaved",
    "chaver",
    "chavers",
    "chavface",
    "chavhead",
    "chavbag",
    "chavwipe",
    "chavhole",
    "chavbucket",
    "chavlord",
    "abbo",
    "abbos",
    "abboy",
    "abboing",
    "abboed",
    "abboer",
    "abboers",
    "abboface",
    "abbohead",
    "abbobag",
    "abbowipe",
    "abbohole",
    "abbobucket",
    "abbolord",
    "ruski",
    "ruskis",
    "ruskiy",
    "ruskiing",
    "ruskied",
    "ruskier",
    "ruskiers",
    "ruskiface",
    "ruskihead",
    "ruskibag",
    "ruskiwipe",
    "ruskihole",
    "ruskibucket",
    "ruskilord",
    "kraut",
    "krauts",
    "krauty",
    "krauting",
    "krauted",
    "krauter",
    "krauters",
    "krautface",
    "krauthead",
    "krautbag",
    "krautwipe",
    "krauthole",
    "krautbucket",
    "krautlord",
    "limey",
    "limeys",
    "limeyy",
    "limeying",
    "limeyed",
    "limeyer",
    "limeyers",
    "limeyface",
    "limeyhead",
    "limeybag",
    "limeywipe",
    "limeyhole",
    "limeybucket",
    "limeylord",
    "squaw",
    "squaws",
    "squawy",
    "squawing",
    "squawed",
    "squawer",
    "squawers",
    "squawface",
    "squawhead",
    "squawbag",
    "squawwipe",
    "squawhole",
    "squawbucket",
    "squawlord",
    "injun",
    "injuns",
    "injuny",
    "injuning",
    "injuned",
    "injuner",
    "injuners",
    "injunface",
    "injunhead",
    "injunbag",
    "injunwipe",
    "injunhole",
    "injunbucket",
    "injunlord",
    "redskin",
    "redskins",
    "redskiny",
    "redskining",
    "redskined",
    "redskiner",
    "redskiners",
    "redskinface",
    "redskinhead",
    "redskinbag",
    "redskinwipe",
    "redskinhole",
    "redskinbucket",
    "redskinlord",
    "pajeet",
    "pajeets",
    "pajeety",
    "pajeeting",
    "pajeeted",
    "pajeeter",
    "pajeeters",
    "pajeetface",
    "pajeethead",
    "pajeetbag",
    "pajeetwipe",
    "pajeethole",
    "pajeetbucket",
    "pajeetlord",
    "raghead",
    "ragheads",
    "ragheady",
    "ragheading",
    "ragheaded",
    "ragheader",
    "ragheaders",
    "ragheadface",
    "ragheadhead",
    "ragheadbag",
    "ragheadwipe",
    "ragheadhole",
    "ragheadbucket",
    "ragheadlord",
    "towelhead",
    "towelheads",
    "towelheady",
    "towelheading",
    "towelheaded",
    "towelheader",
    "towelheaders",
    "towelheadface",
    "towelheadhead",
    "towelheadbag",
    "towelheadwipe",
    "towelheadhole",
    "towelheadbucket",
    "towelheadlord",
    "dothead",
    "dotheads",
    "dotheady",
    "dotheading",
    "dotheaded",
    "dotheader",
    "dotheaders",
    "dotheadface",
    "dotheadhead",
    "dotheadbag",
    "dotheadwipe",
    "dotheadhole",
    "dotheadbucket",
    "dotheadlord",
    "muzzie",
    "muzzies",
    "muzziey",
    "muzzieing",
    "muzzieed",
    "muzzieer",
    "muzzieers",
    "muzzieface",
    "muzziehead",
    "muzziebag",
    "muzziewipe",
    "muzziehole",
    "muzziebucket",
    "muzzielord",
    "kebab",
    "kebabs",
    "kebaby",
    "kebabing",
    "kebabed",
    "kebaber",
    "kebabers",
    "kebabface",
    "kebabhead",
    "kebabbag",
    "kebabwipe",
    "kebabhole",
    "kebabbucket",
    "kebablord",
    "porchmonkey",
    "porchmonkeys",
    "porchmonkeyy",
    "porchmonkeying",
    "porchmonkeyed",
    "porchmonkeyer",
    "porchmonkeyers",
    "porchmonkeyface",
    "porchmonkeyhead",
    "porchmonkeybag",
    "porchmonkeywipe",
    "porchmonkeyhole",
    "porchmonkeybucket",
    "porchmonkeylord",
    "junglebunny",
    "junglebunnys",
    "junglebunnyy",
    "junglebunnying",
    "junglebunnyed",
    "junglebunnyer",
    "junglebunnyers",
    "junglebunnyface",
    "junglebunnyhead",
    "junglebunnybag",
    "junglebunnywipe",
    "junglebunnyhole",
    "junglebunnybucket",
    "junglebunnylord",
    "spearchucker",
    "spearchuckers",
    "spearchuckery",
    "spearchuckering",
    "spearchuckered",
    "spearchuckerer",
    "spearchuckerers",
    "spearchuckerface",
    "spearchuckerhead",
    "spearchuckerbag",
    "spearchuckerwipe",
    "spearchuckerhole",
    "spearchuckerbucket",
    "spearchuckerlord",
    "tarbaby",
    "tarbabys",
    "tarbabyy",
    "tarbabying",
    "tarbabyed",
    "tarbabyer",
    "tarbabyers",
    "tarbabyface",
    "tarbabyhead",
    "tarbabybag",
    "tarbabywipe",
    "tarbabyhole",
    "tarbabybucket",
    "tarbabylord",
    "darkie",
    "darkies",
    "darkiey",
    "darkieing",
    "darkieed",
    "darkieer",
    "darkieers",
    "darkieface",
    "darkiehead",
    "darkiebag",
    "darkiewipe",
    "darkiehole",
    "darkiebucket",
    "darkielord",
    "pickaninny",
    "pickaninnys",
    "pickaninnyy",
    "pickaninnying",
    "pickaninnyed",
    "pickaninnyer",
    "pickaninnyers",
    "pickaninnyface",
    "pickaninnyhead",
    "pickaninnybag",
    "pickaninnywipe",
    "pickaninnyhole",
    "pickaninnybucket",
    "pickaninnylord",
    "sambo",
    "sambos",
    "samboy",
    "samboing",
    "samboed",
    "samboer",
    "samboers",
    "samboface",
    "sambohead",
    "sambobag",
    "sambowipe",
    "sambohole",
    "sambobucket",
    "sambolord",
    "spook",
    "spooks",
    "spooky",
    "spooking",
    "spooked",
    "spooker",
    "spookers",
    "spookface",
    "spookhead",
    "spookbag",
    "spookwipe",
    "spookhole",
    "spookbucket",
    "spooklord",
    "zipperhead",
    "zipperheads",
    "zipperheady",
    "zipperheading",
    "zipperheaded",
    "zipperheader",
    "zipperheaders",
    "zipperheadface",
    "zipperheadhead",
    "zipperheadbag",
    "zipperheadwipe",
    "zipperheadhole",
    "zipperheadbucket",
    "zipperheadlord",
    "slanteye",
    "slanteyes",
    "slanteyey",
    "slanteyeing",
    "slanteyeed",
    "slanteyeer",
    "slanteyeers",
    "slanteyeface",
    "slanteyehead",
    "slanteyebag",
    "slanteyewipe",
    "slanteyehole",
    "slanteyebucket",
    "slanteyelord",
    "sh1t",
    "5hit",
    "$hit",
    "b1tch",
    "d1ck",
    "c0ck",
    "pu55y",
    "pu$$y",
    "4rse",
    "@rse",
    "ars3",
    "ar5e",
    "ar$e",
    "4ss",
    "@ss",
    "a55",
    "a$$",
    "tw4t",
    "tw@t",
    "pr1ck",
    "5lut",
    "$lut",
    "whor3",
    "wh0re",
    "f4g",
    "f@g",
    "ret4rd",
    "ret@rd",
    "r3tard",
    "sp4stic",
    "sp@stic",
    "spast1c",
    "5pa5tic",
    "$pa$tic",
    "crippl3",
    "cr1pple",
    "m0r0n",
    "imb3cil3",
    "1mbec1le",
    "m0ng",
    "douch3",
    "d0uche",
    "w4nk",
    "w@nk",
    "chod3",
    "ch0de",
    "nigg3r",
    "n1gger",
    "nigg4",
    "nigg@",
    "n1gga",
    "ch1nk",
    "g00k",
    "kik3",
    "k1ke",
    "sp1c",
    "5pic",
    "$pic",
    "wetb4ck",
    "wetb@ck",
    "w3tback",
    "c00n",
    "r3dn3ck",
    "h0nky",
    "w0p",
    "d4go",
    "d@go",
    "dag0",
    "pik3y",
    "p1key",
    "ch4v",
    "ch@v",
    "rusk1",
    "ru5ki",
    "ru$ki",
    "kr4ut",
    "kr@ut",
    "lim3y",
    "l1mey",
    "squ4w",
    "squ@w",
    "5quaw",
    "$quaw",
    "1njun",
    "r3dskin",
    "redsk1n",
    "red5kin",
    "red$kin",
    "r4ghe4d",
    "r@ghe@d",
    "ragh3ad",
    "towelhe4d",
    "towelhe@d",
    "tow3lh3ad",
    "t0welhead",
    "dothe4d",
    "dothe@d",
    "doth3ad",
    "d0thead",
    "muzzi3",
    "muzz1e",
    "keb4b",
    "keb@b",
    "k3bab",
    "p4jeet",
    "p@jeet",
    "paj33t",
  ];

  // ===========================================================================
  // LEET / HOMOGLYPH CHARACTER MAP
  // ===========================================================================
  // Maps obfuscation characters to their base letters. Applied to BOTH the
  // input text and the bad-word list so that "b1tch", "b!tch", "5h1t", "@ss"
  // all collapse to their roots.
  //   @ -> a    (at sign)        4 -> a    (four)
  //   8 -> b    (eight)          3 -> e    (three, mirrored)
  //   1 -> i    (one)            ! -> i    (exclamation)
  //   | -> i    (pipe)           0 -> o    (zero)
  //   5 -> s    (five)           $ -> s    (dollar)
  //   7 -> t    (seven)          9 -> g    (nine)
  //   2 -> z    (two)
  // Unicode homoglyphs (Cyrillic, Greek lookalikes) are handled by the
  // NFKD normalization + non-ASCII stripping pass below.
  // ===========================================================================

  var leetMap = {
    '@': 'a',
    '4': 'a',
    '8': 'b',
    '3': 'e',
    '1': 'i',
    '!': 'i',
    '|': 'i',
    '0': 'o',
    '5': 's',
    '$': 's',
    '7': 't',
    '9': 'g',
    '2': 'z'
  };

  // ===========================================================================
  // NORMALIZATION FUNCTIONS
  // ===========================================================================
  // Every function below operates character-by-character using charCodeAt.
  // No regular expression literals appear anywhere in this file — all
  // pattern matching is done through new RegExp() with string-built
  // patterns, which also makes the file immune to minifier and transport
  // escaping bugs.
  // ===========================================================================

  // Applies the leet/homoglyph map to a string.
  // Example: "b1tch" -> "bitch", "@ss" -> "ass", "5h1t" -> "shit"
  function applyLeetMap(s) {
    var result = '';
    for (var i = 0; i < s.length; i++) {
      var c = s[i];
      if (leetMap[c]) {
        result += leetMap[c];
      } else {
        result += c;
      }
    }
    return result;
  }

  // Strips zero-width / invisible characters used to break words apart:
  //   U+200B zero-width space, U+200C ZWNJ, U+200D ZWJ,
  //   U+FEFF BOM, U+00AD soft hyphen
  // Example: "f<ZWSP>uck" -> "fuck"
  function removeZeroWidth(s) {
    var result = '';
    for (var i = 0; i < s.length; i++) {
      var code = s.charCodeAt(i);
      if (code === 0x200B) continue;
      if (code === 0x200C) continue;
      if (code === 0x200D) continue;
      if (code === 0xFEFF) continue;
      if (code === 0x00AD) continue;
      result += s[i];
    }
    return result;
  }

  // Removes combining diacritical marks (U+0300..U+036F) plus any remaining
  // non-ASCII characters. Call AFTER NFKD normalization, which splits
  // accented characters into base + combining mark.
  // Example (post-NFKD): "e" + combining acute -> "e"
  function stripDiacritics(s) {
    var result = '';
    for (var i = 0; i < s.length; i++) {
      var code = s.charCodeAt(i);
      if (code >= 0x0300 && code <= 0x036F) continue;
      if (code > 127) continue;
      result += s[i];
    }
    return result;
  }

  // Keeps only a-z, space, and (optionally) 0-9. Strips punctuation and
  // symbols inserted between letters.
  // Example: "f.u.c.k" -> "fuck", "f-u-c-k" -> "fuck"
  function stripNonAlpha(s, keepDigits) {
    var result = '';
    for (var i = 0; i < s.length; i++) {
      var code = s.charCodeAt(i);
      if (code >= 97 && code <= 122) {
        result += s[i];
      } else if (keepDigits && code >= 48 && code <= 57) {
        result += s[i];
      } else if (code === 32) {
        result += s[i];
      }
    }
    return result;
  }

  // Collapses any immediately-repeated character: "fuuuck" -> "fuck",
  // "shiiit" -> "shit", "ffuuuucckk" -> "fuck". Word-boundary matching
  // keeps this safe: "grass" collapsing to "gras" cannot create a hit
  // because "ass" only matches as a complete word.
  function collapseRepeats(s) {
    var result = '';
    for (var i = 0; i < s.length; i++) {
      var c = s.charAt(i);
      if (result.length > 0 && result.charAt(result.length - 1) === c) {
        continue;
      }
      result += c;
    }
    return result;
  }

  // Collapses runs of whitespace to single spaces and trims the ends.
  function collapseSpaces(s) {
    var result = '';
    var prevSpace = false;
    for (var i = 0; i < s.length; i++) {
      var code = s.charCodeAt(i);
      if (code === 32 || code === 9 || code === 10 || code === 13) {
        if (!prevSpace) {
          result += ' ';
        }
        prevSpace = true;
      } else {
        result += s[i];
        prevSpace = false;
      }
    }
    var a = 0;
    var b = result.length;
    while (a < b && result.charAt(a) === ' ') { a++; }
    while (b > a && result.charAt(b - 1) === ' ') { b--; }
    return result.substring(a, b);
  }

  // Merges runs of short tokens (1-2 chars, at least two in a row) into a
  // single word so split-up obfuscation is caught: "f u c k" -> "fuck",
  // "fu ck" -> "fuck", "ni gg er" -> "nigger". A lone short token passes
  // through unchanged, so ordinary words like "a" or "to" are never merged
  // with their neighbors.
  function mergeShortRuns(s) {
    if (!s) {
      return s;
    }
    var tokens = s.split(' ');
    var out = [];
    var buffer = [];
    var i, j;
    for (i = 0; i < tokens.length; i++) {
      if (tokens[i].length <= 2) {
        buffer.push(tokens[i]);
      } else {
        if (buffer.length >= 2) {
          out.push(buffer.join(''));
        } else {
          for (j = 0; j < buffer.length; j++) {
            out.push(buffer[j]);
          }
        }
        buffer = [];
        out.push(tokens[i]);
      }
    }
    if (buffer.length >= 2) {
      out.push(buffer.join(''));
    } else {
      for (j = 0; j < buffer.length; j++) {
        out.push(buffer[j]);
      }
    }
    return out.join(' ');
  }

  // ---------------------------------------------------------------------------
  // normalize(text, leet) — the full pipeline
  //   1. lowercase            2. NFKD normalize
  //   3. strip diacritics     4. strip zero-width chars
  //   5. leet map (optional)  6. strip separators
  //   7. collapse + trim     8. merge short-token runs
  //   9. collapse repeats
  // ---------------------------------------------------------------------------
  function normalize(text, leet) {
    var s = String(text || '').toLowerCase();
    if (s.normalize) {
      s = s.normalize('NFKD');
    }
    s = stripDiacritics(s);
    s = removeZeroWidth(s);
    if (leet) {
      s = applyLeetMap(s);
    }
    s = stripNonAlpha(s, !leet);
    s = collapseSpaces(s);
    s = mergeShortRuns(s);
    s = collapseRepeats(s);
    return s;
  }

  // ===========================================================================
  // REGEX BUILDER
  // ===========================================================================
  // Builds a single boundary-anchored alternation regex from the word list:
  //   (?:^| )(?:word1|word2|...)(?: |$)
  //
  // The leading group requires a match to start at a word boundary (start of
  // the string or a space), and the trailing group requires it to end at one
  // — so "class", "grass", "assess", and "Scunthorpe" never false-trigger on
  // "ass" / "cunt".
  //
  // Two regexes are built and both are checked for every input:
  //   rawRegex  (leet=false) — keeps digits so numeric slurs like "420" hit
  //   leetRegex (leet=true)  — maps digits/symbols so "b1tch", "@ss" hit
  // ===========================================================================

  // Backslash via fromCharCode — no backslash literals anywhere in this file
  var BACKSLASH = String.fromCharCode(92);

  var regexSpecialChars = {
    '.': true, '*': true, '+': true, '?': true,
    '^': true, '$': true, '{': true, '}': true,
    '(': true, ')': true, '|': true, '[': true, ']': true
  };
  regexSpecialChars[BACKSLASH] = true;

  function escapeRegex(s) {
    var result = '';
    for (var i = 0; i < s.length; i++) {
      if (regexSpecialChars[s[i]]) {
        result += BACKSLASH;
      }
      result += s[i];
    }
    return result;
  }

  function buildRegex(leet) {
    var set = {};
    var hasWords = false;
    for (var i = 0; i < badWords.length; i++) {
      var n = normalize(badWords[i], leet);
      if (n.length >= 2) {
        set[n] = true;
        hasWords = true;
      }
    }
    if (!hasWords) {
      return null;
    }
    var words = [];
    for (var key in set) {
      if (set.hasOwnProperty(key)) {
        words.push(key);
      }
    }
    // Longest first so "motherfucker" wins over "fuck"
    words.sort(function (a, b) {
      return b.length - a.length;
    });
    var pattern = '';
    for (var j = 0; j < words.length; j++) {
      if (j > 0) {
        pattern += '|';
      }
      pattern += escapeRegex(words[j]);
    }
    return new RegExp('(?:^| )(?:' + pattern + ')(?: |$)');
  }

  // Built once at load time and kept private — the console cannot reach,
  // replace, or neuter these references.
  var rawRegex = buildRegex(false);
  var leetRegex = buildRegex(true);

  // ===========================================================================
  // PROFANITY VERIFICATION
  // ===========================================================================
  // The core check. Uses the PRIVATE closure regexes — even if someone
  // overwrites window.containsBadWords in dev tools, the auto-attach event
  // path below keeps calling this inner function, so the filter keeps
  // working.
  // ===========================================================================

  function containsBadWords(message) {
    if (!message || typeof message !== 'string') {
      return false;
    }
    var raw = normalize(message, false);
    var leet = normalize(message, true);
    if (rawRegex && rawRegex.test(raw)) {
      return true;
    }
    if (leetRegex && leetRegex.test(leet)) {
      return true;
    }
    return false;
  }

  // ===========================================================================
  // TAMPER-PROOF LAYER 1: INTEGRITY CHECK
  // ===========================================================================
  // A rolling hash of the word list is computed at load time and stored in a
  // private closure variable. A periodic verifier recomputes the hash and
  // compares it. If someone empties or mutates the array via dev tools, the
  // filter restores its private backup and rebuilds both regexes. The backup
  // lives inside the closure and cannot be reached from the console, so the
  // restore always succeeds.
  // ===========================================================================

  function computeWordHash() {
    var h = 5381;
    var i, j, w;
    for (i = 0; i < badWords.length; i++) {
      w = badWords[i];
      for (j = 0; j < w.length; j++) {
        h = ((h << 5) + h + w.charCodeAt(j)) | 0;
      }
      h = (h + i * 31) | 0;
    }
    return h;
  }

  // Private backup of the word list — unreachable from dev tools
  var wordListBackup = badWords.slice();
  var wordHash = computeWordHash();

  function verifyIntegrity() {
    if (computeWordHash() !== wordHash) {
      badWords = wordListBackup.slice();
      wordHash = computeWordHash();
      rawRegex = buildRegex(false);
      leetRegex = buildRegex(true);
    }
  }

  // ===========================================================================
  // TAMPER-PROOF LAYER 2: ANTI-DEBUG TIMER
  // ===========================================================================
  // If a debugger statement pauses execution, the gap between ticks
  // balloons. The next tick detects it and re-verifies integrity plus
  // re-attaches listeners — defeating pause-and-tamper attempts.
  // ===========================================================================

  var lastTick = Date.now();
  setInterval(function () {
    var now = Date.now();
    if (now - lastTick > 5000) {
      verifyIntegrity();
      attachFilterToAllInputs();
    }
    lastTick = now;
  }, 1000);

  // ===========================================================================
  // TAMPER-PROOF LAYER 3: SECRET OVERRIDE COMMAND
  // ===========================================================================
  // The ONLY way to disable the filter. The _disabled flag lives in the
  // closure; overwriting window.__badwordOverride does not affect it, and
  // no console assignment can reach it. The correct key toggles the filter
  // off; calling again re-enables it.
  // ===========================================================================

  var _disabled = false;

  try {
    Object.defineProperty(window, '__badwordOverride', {
      value: function (key) {
        if (key === 'FORGE-MASTER-2026') {
          _disabled = !_disabled;
          return _disabled ? 'FILTER DISABLED' : 'FILTER RE-ENABLED';
        }
        return 'INVALID KEY';
      },
      writable: false,
      configurable: false
    });
  } catch (err) {
    window.__badwordOverride = function (key) {
      if (key === 'FORGE-MASTER-2026') {
        _disabled = !_disabled;
        return _disabled ? 'FILTER DISABLED' : 'FILTER RE-ENABLED';
      }
      return 'INVALID KEY';
    };
  }

  // ===========================================================================
  // WARNING MODAL UI
  // ===========================================================================
  // Minimal self-contained dark terminal-style dialog. No external CSS,
  // fonts, or images — everything inline.
  // ===========================================================================

  var MODAL_CSS = [
    '.bw-overlay{position:fixed;top:0;left:0;right:0;bottom:0;',
    'background:rgba(0,0,0,0.78);z-index:2147483647;',
    'display:none;align-items:center;justify-content:center;',
    'font-family:monospace;}',
    '.bw-box{background:#111827;border:1px solid #10b981;',
    'border-radius:8px;padding:28px 32px;max-width:340px;text-align:center;}',
    '.bw-title{color:#ef4444;font-size:15px;font-weight:bold;',
    'letter-spacing:2px;margin-bottom:10px;}',
    '.bw-msg{color:#9ca3af;font-size:13px;line-height:1.5;margin-bottom:18px;}',
    '.bw-btn{background:#10b981;color:#0b0f19;border:none;border-radius:4px;',
    'padding:8px 32px;font-family:monospace;font-size:13px;letter-spacing:1px;',
    'cursor:pointer;}',
    '.bw-btn:hover{background:#059669;}'
  ].join('');

  try {
    var styleEl = document.createElement('style');
    styleEl.textContent = MODAL_CSS;
    (document.head || document.documentElement).appendChild(styleEl);
  } catch (err) { /* non-fatal: modal falls back to unstyled display */ }

  var modalEl = null;

  function ensureModal() {
    if (modalEl && document.body && document.body.contains(modalEl)) return;
    if (!document.body) return;
    modalEl = document.createElement('div');
    modalEl.className = 'bw-overlay';
    var box = document.createElement('div');
    box.className = 'bw-box';
    var title = document.createElement('div');
    title.className = 'bw-title';
    title.textContent = 'PROFANITY DETECTED';
    var msg = document.createElement('div');
    msg.className = 'bw-msg';
    msg.textContent = 'Your input contains prohibited language and has been removed.';
    var btn = document.createElement('button');
    btn.className = 'bw-btn';
    btn.textContent = 'OK';
    btn.addEventListener('click', function () {
      modalEl.style.display = 'none';
    });
    box.appendChild(title);
    box.appendChild(msg);
    box.appendChild(btn);
    modalEl.appendChild(box);
    document.body.appendChild(modalEl);
  }

  function showModal() {
    ensureModal();
    if (modalEl) modalEl.style.display = 'flex';
  }

  // ===========================================================================
  // FIELD DETECTION
  // ===========================================================================
  // Identifies elements that accept user text: text inputs, textareas, and
  // contenteditable regions. Password fields included — profanity in a
  // password is still profanity.
  // ===========================================================================

  function isTextField(el) {
    if (!el || !el.tagName) return false;
    var tag = el.tagName.toUpperCase();
    if (tag === 'TEXTAREA') return true;
    if (tag === 'INPUT') {
      var type = ((el.getAttribute && el.getAttribute('type')) || 'text').toLowerCase();
      if (type === 'text' || type === 'search' || type === 'email' ||
          type === 'url' || type === 'tel' || type === 'password' || type === '') {
        return true;
      }
      return false;
    }
    if (el.isContentEditable) return true;
    return false;
  }

  // ===========================================================================
  // SHARED INPUT HANDLER
  // ===========================================================================
  // A SINGLE function reference is attached to every field. This is the key
  // to tamper-resistance: addEventListener ignores duplicate bindings of the
  // same function, so the self-healing tick can safely re-attach to every
  // field over and over. Removing a listener via dev tools is undone on the
  // very next heal tick.
  // ===========================================================================

  function sharedHandler(e) {
    if (_disabled) return;
    var el = e.target || e.srcElement;
    if (!el || !isTextField(el)) return;
    var value = el.isContentEditable ? (el.textContent || '') : (el.value || '');
    if (!value) return;
    // PRIVATE closure reference — overriding window.containsBadWords has no
    // effect on this call path
    if (containsBadWords(value)) {
      el.__bwViolationCount = (el.__bwViolationCount || 0) + 1;
      if (el.isContentEditable) {
        el.textContent = '';
      } else {
        el.value = '';
      }
      showModal();
    }
  }

  // ===========================================================================
  // ATTACHMENT API
  // ===========================================================================

  function attachFilterToInput(el) {
    if (!el || !el.addEventListener) return;
    el.addEventListener('input', sharedHandler);
    if (el.isContentEditable) {
      el.addEventListener('blur', sharedHandler);
    }
  }

  function attachFilterToAllInputs() {
    var list = document.querySelectorAll('input, textarea, [contenteditable]');
    for (var i = 0; i < list.length; i++) {
      attachFilterToInput(list[i]);
    }
  }

  // ===========================================================================
  // AUTO-ATTACH ON LOAD + SELF-HEALING OBSERVER
  // ===========================================================================
  // Attach to all existing fields once the DOM is ready, then keep a
  // MutationObserver on the document so dynamically added fields (SPA
  // routes, chat widgets, comment forms) are filtered the instant they
  // appear. A periodic heal tick re-attaches everything and re-verifies
  // integrity — idempotent by design.
  // ===========================================================================

  function startObserver() {
    if (!window.MutationObserver) return;
    var target = document.documentElement || document.body;
    if (!target) {
      setTimeout(startObserver, 50);
      return;
    }
    var mo = new MutationObserver(function () {
      attachFilterToAllInputs();
    });
    mo.observe(target, { childList: true, subtree: true });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', function () {
      attachFilterToAllInputs();
      startObserver();
    });
  } else {
    attachFilterToAllInputs();
    startObserver();
  }

  // Periodic self-healing: re-verify the word list, re-attach all listeners
  setInterval(function () {
    verifyIntegrity();
    attachFilterToAllInputs();
  }, 1500);

  // ===========================================================================
  // GLOBAL EXPOSURE (FROZEN)
  // ===========================================================================
  // The public API is defined on window with writable:false and
  // configurable:false — console reassignment silently fails. Even if a
  // hostile environment somehow replaces them, the internal auto-attach
  // path never touches these globals; it uses private closure references.
  // ===========================================================================

  function expose(name, fn) {
    try {
      Object.defineProperty(window, name, {
        value: fn,
        writable: false,
        configurable: false
      });
    } catch (err) {
      window[name] = fn;
    }
  }

  expose('containsBadWords', containsBadWords);
  expose('attachFilterToInput', attachFilterToInput);
  expose('attachFilterToAllInputs', attachFilterToAllInputs);

  // Belt-and-suspenders: if the globals were somehow swapped (older browsers,
  // pre-existing writable properties), restore them every few seconds.
  setInterval(function () {
    if (window.containsBadWords !== containsBadWords) {
      try {
        window.containsBadWords = containsBadWords;
      } catch (err) { /* ignore */ }
    }
  }, 2000);

  // ===========================================================================
  // END OF badword.js
  // ===========================================================================
  // Summary of protections:
  //   1. Closure isolation — internals unreachable from dev tools
  //   2. Integrity check — tampered word list auto-restored and rebuilt
  //   3. Anti-debug timer — pause-and-tamper reverted on resume
  //   4. Frozen API — globals cannot be reassigned
  //   5. Self-healing — removed listeners re-attached within 1.5s
  //   6. MutationObserver — dynamic fields filtered on arrival
  //   7. Secret override — the only disable path:
  //        window.__badwordOverride('FORGE-MASTER-2026')
  // ===========================================================================
})();
